### ISSUE TITLE
Do you have any more examples

### ISSUE THREAD

**Issue by kinlik233** [tybl/BallSort#1]
I'm working on a game，I need these examples as levels for the game。Because I'm a rookie, it's a little difficult for me to make these levels。
Thank you for your help。Here is my E-mail    kinlik233@gmail.com

**Comment by tybl** [comment]
Hi @kinlik233,
I may upload some new examples as I generate them, but it may be a while before that happens. The examples are really just the input files I've written to help me solve the levels of [this game](https://play.google.com/store/apps/details?id=com.spicags.ballsort). However, I have advanced to a level of the game that has taller tubes. This would require refactoring the source code to work with both the 4 and 5 ball tubes. I should probably go ahead and add an issue to refactor for that.

**Comment by tybl** [comment]
Created #2 to refactor for dynamic stack heights
